version: 2

jobs:
    build:
        working_directory: ~/aptotude
        docker:
            # LTS version
            - image: circleci/node:10.13.0-browsers
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - "9f:c3:e6:09:34:eb:6f:00:c0:ab:1d:d9:05:06:e8:3b"
            - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            - run: yarn install
            - run: yarn lint

            # Create a new github release
            - run: >
                if [ "$CIRCLE_BRANCH" == "master" ]; then
                    echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
                    npm run release
                fi

workflows:
    version: 2

    #Perform build and unit tests on every commit
    commit-workflow:
      jobs:
        - build
