version: 2

jobs:
    build:
        working_directory: ~/aptotude
        docker:
            # LTS version
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - "11:a6:53:82:37:02:4a:b7:61:66:4b:2f:2c:41:48:17"
            - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            - run: yarn install
            - run: yarn format:check
            - run: yarn lint
            # - run: yarn test
            # Create a new github release
            - run: >
                if [ "$CIRCLE_BRANCH" == "master" ]; then
                    echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
                    npm run release
                fi

workflows:
    version: 2

    #Perform build and unit tests on every commit
    commit-workflow:
      jobs:
        - build
